apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubo-server
  template:
    metadata:
      labels:
        app: kubo-server
    spec: 
      containers:
        - name: kubo-server
          image: us-central1-docker.pkg.dev/kubo-448922/kubo-server/server:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kubo-server-service
spec:
  type: LoadBalancer
  selector:
    app: kubo-server
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 3000
